main: kp.node.kuroplugin
version: 1.0.0
name: kuroplugin
author: node
api-version: 1.13

commands:
  InfiniteVillagerTrades:
    description: "Activate Infinite Villager Trades."
    usage: "/InfiniteVillagerTrades"
    aliases:
      - ivt

  InfiniteVillagerTradesOff:
    description: "Deactivate Infinite Villager Trades."
    usage: "/InfiniteVillagerTradesOff"
    aliases:

  warp:
    description: "Manage and teleport to warps"
    usage: "/warp or /warp <warpName>"
    aliases:
      - w

  setWarp:
    description: "Set a new warp"
    usage: "/setWarp <warpName>"
    aliases:
      - sw

  delwarp:
    description: "Delete a warp"
    usage: "/delwarp <warpName>"
    aliases:
      - dw